version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release  

before_build:
  - nuget restore src\TestLib.sln

build:
  project: src\TestLib.sln

after_test:
  - nuget pack TestLib.nuspec -Version $env:appveyor_build_version

artifacts:
  - path: src\TestLib\bin\Release\TestLib.dll
    name: TestLib.dll
  - path: '*.nupkg'
  
deploy:
  provider: NuGet
  api_key:
    secure: 1b2+bxbWw/urAQ8b9c2N11DmYv/+MjTEvCgE/ZGw2WFfJXKGeXCPBqYkkuHe8HWN
  artifact: /.*\.nupkg/